seed:
  torch_manual_seed: 1025
  cuda_manual_seed: 1025
deterministic:
  backends_cudnn_deterministic: False # True を指定すると遅くなる...
  use_deterministic_algorithms: True

source_data:
  classes: [
      "aeroplane",
      "bicycle",
      "bird",
      "boat",
      "bottle",
      "bus",
      "car",
      "cat",
      "chair",
      "cow",
      "diningtable",
      "dog",
      "horse",
      "motorbike",
      "person",
      "pottedplant",
      "sheep",
      "sofa",
      "train",
      "tvmonitor"
  ]
  dir_path: data/VOCdevkit/VOC2012/

data_loader:
  batch_size: 32
  num_workers: 2

model:
  ssd_config:
    num_classes: 21
    image_size: 300
    bbox_aspect_num: [4, 6, 6, 6, 4, 4]
    feature_map_regions: [38, 19, 10, 5, 3, 1]
    region_sizes: [8, 16, 32, 64, 100, 300]
    min_sizes: [30, 60, 111, 162, 213, 264]
    max_sizes: [60, 111, 162, 213, 264, 315]
    aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
  initial_weight:
    vgg: weights/vgg/vgg16_reducedfc.pth

criterion:
  jaccard_thresh: 0.5
  negpos_ratio: 3

optimizer:
  SGD:
    learning_rate: 1e-3
    momentum: 0.9
    weight_decay: 5e-4
  scheduler:
    # 経過 epoch 数ごとに学習率を減少(gamma 倍)
    # -   0〜174 epoch: lr
    # - 175〜249 epoch: lr * gamma
    # - 250〜    epoch: lr * gamma^2
    gamma: 0.1
    milestones: [175, 250]

train:
  epochs: 300
  iters_per_log: 10
  epochs_per_log: 10
  epochs_per_save: 10
  model_weight_output_dir: weights/models
  last_iteration: 0
  additional_learning: False
  base_model_path: weights/models/ssd300_300.pth
  base_optimizer_path: weights/models/optimizer_300.pth
  base_scheduler_path: weights/models/scheduler_300.pth
